import { Header } from "@/features/layout/Header";
import { Providers } from "@/lib/providers";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/theme/ThemeProvider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Vocabulary",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("h-full")}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          <Providers>
            <div className="space-y-4 font-playpenSans">
              <Header />
              <div className="max-w-2xl m-auto">{children}</div>
            </div>
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
